feat: t1 - existance of files
KrawczowaKris/devops-camp-2023 pull request #1
Opened 2023-03-28 11:30 UTC by KrawczowaKris

# Summary
## Test Task
**T1 - Existance of files**
-    write bash shell script that accepts two arguments with filenames.
-    script should verify if those files exists and if so - output the content of these files, otherwise
-    it should create these files in a local directory with rwx------ permission set
-    each file should contain a random string encoded in base64 format.

## my results
`./chapter2-t1-two-files.sh f.txt a.txt`

**output:**
`AH1srYrkGq0=`
`6g9CAo0jPKo=`

Or files are created.

2023-03-29 03:57 UTC, kseniyashaydurova requested changes

2023-03-29 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +#!/bin/bash
Please add in each PR link to a corresponding task, now it takes time to find out task description - https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter2%20-%20bash%20basics/l1%20-%20bash%20basics.md#t1---existance-of-files

2023-03-29 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +func $1
As I see your script doesn't accept 2 arguments at the same time, it accepts only one.

2023-03-29 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $1 ]
1. Please format if/else conditions in nicer manner, then it would be much easier to read it, i.e.

```
if [ -f "$FILE" ]; then
    cat $FILE
else 
    touch $FILE
    ...
fi
```

2. Also it is a good practice to add names to function vars instead of just using `$1` or `$2`, it improves code readability a lot especially for people who doesn't know what your code should do, i.e.

```
local file=$1
echo $file
``` 

3. Please name functions with something meaningful, i.e. you should understand or at least guess what function does from name, so you could name it `get_or_create_file` or smth else. Also please add docs above each function with explanation, what arguments it takes. Like this:

```
#
# get_or_create_file -- show contents of existing file or create a new one if it doesn't exist...
#
# usage: get_or_create_file <FILENAME1> <FILENAME2>
#
get_or_create_file () {...}
```

2023-03-29 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	else touch $1; chmod 700 $1; openssl rand -base64 8 > $1
You can do just, no need for `touch $1` above, because `> $1` will create new file if it doesn't exist

```
openssl rand -base64 8 > $1
chmod 700 $1
```

2023-03-29 08:12 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +#!/bin/bash
done

2023-03-29 08:28 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	else touch $1; chmod 700 $1; openssl rand -base64 8 > $1
done

2023-03-29 08:32 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +func $1
done

2023-03-29 08:41 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $1 ]
Tell me please, only functions need to be signed?

2023-03-30 05:56 UTC, roman-mightydevops requested changes

2023-03-30 05:56 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +file_2=$2
> write bash shell script that accepts two arguments with filenames

But it will accept 0 or 3 arguments and complete with success.

2023-03-30 05:56 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in $file_1, $file_2; do
The trailing comma is part of the value, not a separator. Delete or quote it.
``` 
./script.sh foo bar
ls
bar  foo,  script.sh
```

2023-03-30 05:56 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
Always quote strings containing variables.
```suggestion
	if [ -f "$FILE" ]
```

2023-03-30 05:56 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
Indent with 2 spaces instead of tabs.

2023-03-30 08:52 UTC, kseniyashaydurova requested changes

2023-03-30 08:52 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +file_1=$1
Please use this styleguide and add docs and vars according to it - https://google.github.io/styleguide/shellguide.html#constants-and-environment-variable-names

So here you have constants, so please format them properly

2023-03-30 08:52 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
Writing `if` conditions in this way looks much better:
```
	if [ -f $FILE ]; then
                cat $FILE
	else
		openssl rand -base64 8 > $FILE;
		chmod 700 $FILE
	fi
```

or like this

```
	if [ -f $FILE ]
        then
                cat $FILE
	else
		openssl rand -base64 8 > $FILE;
		chmod 700 $FILE
	fi
```

2023-03-30 08:52 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
Please add some separator between 2 files, so we could separate its content. So you can do smth like:
```
file1.txt
--------------
.....

file2.txt
--------------
......
```

2023-03-30 10:06 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +file_2=$2
done

2023-03-30 10:07 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in $file_1, $file_2; do
done

2023-03-30 10:08 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
done

2023-03-30 10:09 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
done

2023-03-30 10:10 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +file_1=$1
done

2023-03-30 10:13 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
done

2023-03-30 10:18 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
done

2023-03-31 05:16 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
No it's not 🥲

2023-03-31 05:27 UTC, roman-mightydevops requested changes

2023-03-31 05:27 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in $FILE_1 $FILE_2; do
What if I want my files being named with spaces (cause Linux says I can)?
```
ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (plumbing) ~/TEMP/camp
➜ ls
chapter2-t1-two-files.sh

ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (plumbing) ~/TEMP/camp
➜ ./chapter2-t1-two-files.sh 'my file' 'my second file'
Hwt1KA4dUB4=
--------------
iH2m1afeNsM=
--------------

ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (plumbing) ~/TEMP/camp
➜ ls
chapter2-t1-two-files.sh  file  my  second
```
That's why when I wrote to always quote variables I meant it. Otherwise your variables might be split by shell when you don't expect.

2023-03-31 06:19 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +	if [ -f $FILE ]
right now?

2023-03-31 06:20 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in $FILE_1 $FILE_2; do
ok

2023-04-03 02:51 UTC, kseniyashaydurova requested changes

2023-04-03 02:51 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +FILE_1="$1"
No need to define separate `FILE_1` and `FILE_2` vars for this case, you can loop over arguments passed to script - https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch05s08.html

2023-04-03 02:51 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
Please add filename above file content (similar to my example)

2023-04-03 05:04 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +		then cat $FILE
Added

2023-04-03 05:07 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +FILE_1="$1"
done

2023-04-03 05:44 UTC, roman-mightydevops requested changes
Please handle this case (when user doesn't have the access to specified path). You can print your own error message, or just pretend the file doesn't exist and move on.

```
➜ ./test.sh /root/test /home/user/test1
./test.sh: line 16: /root/test: Permission denied
chmod: cannot access '/root/test': Permission denied
./test.sh: line 16: /home/user/test1: Permission denied
chmod: cannot access '/home/user/test1': No such file or directory
```

Also, output is a bit messy, at least add an empty line (or some other separator) between files
```
✗  ./chapter2-t1-two-files.sh 'my file' 'my second file'
my file
QhQyvkIR26c=
my second file
+8B6QYKxMwY=
```

2023-04-03 08:15 UTC, roman-mightydevops requested changes

2023-04-05 04:12 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +FILE_1="$1"
Please check out this https://itslinuxfoss.com/difference-between-ampersand-and-asterisk-bash/

2023-04-05 04:20 UTC, kseniyashaydurova requested changes

2023-04-05 04:20 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in "$1" "$2"; do
![image](https://user-images.githubusercontent.com/26448672/229979409-704bde76-ed0c-4cf2-98f7-25b6e4347eed.png)
1. Not nice file content output (if file has no empty string at the end - check README.md)
2. Now new files are not created anymore, there is always `is not writable` code error

2023-04-05 04:20 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +      test -r "$FILE"
Why do you need to make this test again here? You already did it in 13th line

2023-04-05 04:20 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +      echo "--------------"
Let's add separate `separator` function, which will print these output separation symbols

2023-04-05 04:20 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ "$?" -eq 1 ]]; then
Also I suggest to move `test` and `test results IF check` to separate function too, so you will pass params which should be tested, i.e. `-w` or `-r` + `error message`. This function will perform your IF check inside, print error_message if needed and  make exit from script if error appeared

2023-04-06 08:39 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +FILE_1="$1"
thanks, done

2023-04-06 08:47 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    exec 2>/dev/null
done

2023-04-06 08:49 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +      test -r "$FILE"
done

2023-04-06 08:52 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +      echo "--------------"
done

2023-04-07 10:26 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for FILE in "$1" "$2"; do
done

2023-04-07 11:10 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ "$?" -eq 1 ]]; then
done

2023-04-11 11:07 UTC, kseniyashaydurova requested changes

2023-04-11 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ "${folder_access_testing_flag}" -eq 1 ]]; then
I think it is better to inverse logics here and avoid this IF. So you can add `exit 1` in your `folder_access_testing` function, so if file is not writable or readable script will raise with error. so then you will do just:

```
if [ -f "${FILE}" ]; then
    folder_access_testing "${FILE}" -r "readable"
    echo "${FILE}"
    cat "${FILE}"
    separator
```

So we know that in case of not readable/writable file/folder there would be raised error and there is no need in if/else

2023-04-11 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
So in case if we pass to your script not existing filename with some existing dir in path it will raise error that dir is not writable instead of creating new file in current path

![image](https://user-images.githubusercontent.com/26448672/231142042-87a01ddc-94b7-4a20-b8ee-1c2cc486db7d.png)

But when we pass filename without any dir it works as expected (creates a new file in local path)

2023-04-11 11:20 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +folder_access_testing() {
done

2023-04-11 11:22 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  folder_access_testing_flag=0
done

2023-04-11 11:23 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  local test_flag="$2"
done

2023-04-11 11:37 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ "${folder_access_testing_flag}" -eq 1 ]]; then
done

2023-04-11 11:41 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
I didn't quite understand it. Need to create a new folder and a file in it?

2023-04-13 03:57 UTC, kseniyashaydurova requested changes

2023-04-13 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  has_access=0
Let's remove this `has_access` flag? Basically it does nothing, because inside this `test_access` function you do `test "${test_args}" "${FILE}"` command and then you check this command code in if condition `if [[ "$?" -eq 1 ]]; then`, so is command code is not 0 => then command not successful and you `echo` error and make `exit` from script. 

So this `has_access` variable is redundant, because you never check it and etc, you just set it but for no reason.

2023-04-13 03:57 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
You get this error in case if we print file name with existing path, in my example `ats-dart-backend` path is real and existing, but it has no file `INSTALL1.md` inside, so basically this directory is writable, you just don't have such a file there and you should just create `INSTALL1.md` in current local path

2023-04-13 07:31 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  has_access=0
done

2023-04-13 08:25 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
done

2023-04-14 03:47 UTC, kseniyashaydurova requested changes

2023-04-14 03:47 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
It still doesn't work, please check out your `test_access` function, there is error there and that is why it works incorrectly

2023-04-14 07:11 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +    if [[ -d "${FILE%/*}" ]]; then
seems like it should work

2023-04-26 07:45 UTC, roman-mightydevops approved these changes

2023-04-26 07:45 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +test_access() {
Looks like docstring got outdated :)

2023-04-26 07:45 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  test "${test_args}" "${FILE}"
I wonder why declare variables for 2 arguments, but not for 3rd. Also, why var names are in different styles.

2023-04-26 10:30 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +test_access() {
done

2023-04-26 10:35 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +test_access() {
done

2023-04-26 10:35 UTC, KrawczowaKris commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  test "${test_args}" "${FILE}"
done

2023-04-27 03:36 UTC, roman-mightydevops approved these changes

2023-05-03 03:29 UTC, kseniyashaydurova approved these changes

2023-05-12 12:01 UTC, merged