feat: implement your test host
KrawczowaKris/devops-camp-2023 pull request #10
Opened 2023-04-12 10:03 UTC by KrawczowaKris

# Summary
## Test Task
**Implement your test host**
-  setup nginx supporting 2 servers
-  camp-php.local (this will be used for future php experiments)
-  camp-python.local (this will be used for future python experiments)
-  both servers should support named certificates for the domains mentioned above. use `mkcert cli` to do that
-  both server should implement custom location /hello, that will return `200 OK` status code along with the value of the `query_string` passed into that URL, [see here](https://www.techopedia.com/definition/1228/query-string), for example https://camp-php.local/hello?tech_stack=php, which should output the entire query_string
-  your SSL cert should be valid in CURL call in CLI, as well as if you open it in the browser
-  your camp-php.local server should output logs in JSON format
-  open PR when you done, in the PR - pls demonstrate the output of the `curl` call for the URL in each domain, and the screenshot in the browser

## my results

### camp-php.local
`curl -I https://camp-php.local`
```
HTTP/2 200 
server: nginx/1.18.0 (Ubuntu)
date: Wed, 12 Apr 2023 09:54:41 GMT
content-type: text/html
content-length: 199
last-modified: Mon, 10 Apr 2023 07:14:43 GMT
etag: "6433b763-c7"
accept-ranges: bytes
```

screenshot in the browser:
![изображение](https://user-images.githubusercontent.com/72573143/231423870-031cdfa2-5afd-4aaf-8a6e-4f36001ab3c0.png)

logs in json format:
```
{ "@timestamp": "2023-04-12T14:54:41+05:00", "remote_addr": "127.0.0.1", "body_bytes_sent": "0", "status": 200, "request": "HEAD / HTTP/2.0", "url": "/index.html", "request_method": "HEAD", "response_time": 0, "http_referrer": "", "http_user_agent": "curl/7.81.0" }
{ "@timestamp": "2023-04-12T14:57:06+05:00", "remote_addr": "127.0.0.1", "body_bytes_sent": "14", "status": 200, "request": "GET /hello?tech_stack=php HTTP/2.0", "url": "/hello", "request_method": "GET", "response_time": 0, "http_referrer": "", "http_user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" }
```

### camp-python.local
`curl -I https://camp-python.local`
```
HTTP/2 200 
server: nginx/1.18.0 (Ubuntu)
date: Wed, 12 Apr 2023 10:01:08 GMT
content-type: text/html
content-length: 202
last-modified: Mon, 10 Apr 2023 07:14:12 GMT
etag: "6433b744-ca"
accept-ranges: bytes
```

screenshot in the browser:
![изображение](https://user-images.githubusercontent.com/72573143/231425109-0ad696c4-5026-4c44-a9eb-51ecc8ce8951.png)

2023-04-12 19:56 UTC, dmitry-mightydevops requested changes
I only see the log files in the PR - no actual implementation

2023-04-12 19:56 UTC, dmitry-mightydevops commented on chapter2/tests/curl-camp-php.log
no need to store artifacts such as logs. You can attach them in the PR - but don't store in the remote. They're noise.

2023-04-12 19:56 UTC, dmitry-mightydevops commented on chapter2/tests/curl-camp-python.log
Noise in the repo

2023-04-13 03:42 UTC, KrawczowaKris commented on chapter2/tests/curl-camp-php.log
done

2023-04-14 11:02 UTC, KrawczowaKris commented on chapter2/tests/camp-php.local
> +map $upstream_response_time $temprt {
remade

2023-04-15 19:31 UTC, dmitry-mightydevops requested changes

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +		access_log /var/log/nginx/camp-php.local_access.log json;
prefer nothing after you declare `location`. I.e. all your logs should be right after the listen.

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +		listen [::]:80;
no need for 80 if you have a superior 443.

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +		try_files $uri $uri/ =404;
formatting issue.

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +	log_format json '{ "@timestamp": "$time_iso8601", '
make nicer format

```
log_format json_combined escape=json
  '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"request":"$request",'
    '"status": "$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
  '}';
```

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +include /usr/share/nginx/modules/*.conf;
no need for includes, pls always supply self-sufficient single nginx.conf for the sake of debugging.

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +	include /etc/nginx/conf.d/*.conf;
no need for includes for test tasks

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +	include /etc/nginx/mime.types;
that's fine to keep it *the only include you can keep it.

2023-04-15 19:31 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +	default_type application/octet-stream;
if you have multiple "similar" directives - group them.

i.e.

```
include....
default_type
include...
```

is not good for reading.

Same issue with logs. You define the `log_format` and `access_log` in different areas of your `server` context. They should be close to each other.

2023-04-17 08:01 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +		access_log /var/log/nginx/camp-php.local_access.log json;
done

2023-04-17 08:01 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +		listen [::]:80;
done

2023-04-17 08:02 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +		try_files $uri $uri/ =404;
done

2023-04-17 08:09 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +include /usr/share/nginx/modules/*.conf;
removed

2023-04-17 08:09 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +	include /etc/nginx/conf.d/*.conf;
removed

2023-04-17 08:12 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +	default_type application/octet-stream;
remade

2023-04-17 08:26 UTC, KrawczowaKris commented on chapter2/tests/nginx.conf
> +	log_format json '{ "@timestamp": "$time_iso8601", '
better now?

2023-04-18 23:33 UTC, dmitry-mightydevops approved these changes

2023-04-18 23:33 UTC, dmitry-mightydevops commented on chapter2/tests/nginx.conf
> +	log_format json '{ "@timestamp": "$time_iso8601", '
yes much :)

2023-04-28 06:35 UTC, merged