feat: slow php reporting page
KrawczowaKris/devops-camp-2023 pull request #13
Opened 2023-04-20 11:32 UTC by KrawczowaKris

# Summary
## Test Task
**Slow php reporting page**

A typical scenario:
-  you have a web app
-  that app has a backend written in PHP
-  most of the backend works fast and good for end users < 1000ms
-  however there is a slow page /reports/slow, that takes 10m to execute, which causes nginx and php to timeout
-  implement such solution so that nginx/php-fpm do not timeout and get the report when 10m passed.

Implementation nuances:
-  your nginx and php-fpm should run under nginx/nginx user/group.
-  use sleep php func to simulate such report, https://www.php.net/manual/en/function.sleep.php
-  implement a custom location /reports/fast, that will work fast and doesn't require any timeouts, and will use www pool of the PHP-FPM
-  implement a custom location /reports/slow, that will open /tmp/nginx/reports/slow.php script, which will take 10m to execute
-  during the /reports/slow, you should not lose the browser connection to the server.
-  IMPORTANT: you can't change any values for your core application that runs inside www pool defined in the PHP-FPM, for example you can't change timeout via www pool, as that may substantially degrade all the other URLs that are working good and fast - so think how you can do it.

When you open PR - pls package your solution as zip file with bash script run.sh that should
-  create all necessary files and/or folders.
-  set proper permissions to created files/folders
-  start nginx in foreground mode (so all errors, logs are printed on stdout/stderr)
-  start php-fpm in foreground mode (so all errors, logs are printed on stdout/stderr)
-  curl https://localhost/reports/fast should output "FAST REPORT" via PHP script
-  curl https://localhost/reports/slow should output "SLOW REPORT" via PHP script with 10m delay without losing any connection (i.e. no timeout or upstream timeout error in the nginx)

## my results
`curl https://localhost/reports/fast`
**output:**
`FAST REPORT`

`curl https://localhost/reports/slow`
**output:**
After ten minutes:
`SLOW REPORT`

2023-04-20 17:26 UTC, dmitry-mightydevops requested changes

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/nginx.conf
> +			fastcgi_param SCRIPT_FILENAME /var/www/reports/fast.php;
don't use hardcoded value. Find a different approach and use a realpath I have mentioned in the lecture.

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/nginx.conf
> +			fastcgi_param SCRIPT_FILENAME /var/www/reports/slow.php;
Same here

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/php-slow.zip
all binaries should not be pushed in the remote. Attach them to git PR summary.

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/php-fpm.conf
> +[slow]
that is not a correct solution as your "slow" pool has no difference than the www pool. Your timeout group of settings have to be defined as `admin` type value in php-fpm.conf and as well as in the location.

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/php.ini
> +max_execution_timeout = 630s
that has to exists in the php-fpm.conf in a proper pool. Right now you allow ALL SCRIPTS to be super slow.
In our case we still need to timeout in 30s (or 60s) except for the slow pool (that we know ahead of time is always slow)

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +sleep 3
no need for sleep. Check with `while cycle, using CURL call` that nginx is up & running.

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +curl https://localhost/reports/fast
learn how to use `time`, i.e. `time curl <URL>`

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/php.ini
> +max_execution_timeout = 630s
So keep in mind that php.ini is a global file and all settings from php.ini will be applied to all PHP processes until you override them in php-fpm.conf via `value` flags.

2023-04-20 17:26 UTC, dmitry-mightydevops requested changes

2023-04-20 17:26 UTC, dmitry-mightydevops commented on chapter3/php.ini
> +max_execution_time = 30
you duplicate the values. That will have side effects

2023-04-21 06:55 UTC, KrawczowaKris commented on chapter3/php-slow.zip
done

2023-04-21 07:02 UTC, KrawczowaKris commented on chapter3/php.ini
> +max_execution_timeout = 630s
remade

2023-04-21 07:03 UTC, KrawczowaKris commented on chapter3/php.ini
> +max_execution_time = 30
remade

2023-04-21 07:22 UTC, KrawczowaKris commented on chapter3/nginx.conf
> +			fastcgi_param SCRIPT_FILENAME /var/www/reports/fast.php;
done

2023-04-21 07:22 UTC, KrawczowaKris commented on chapter3/nginx.conf
> +			fastcgi_param SCRIPT_FILENAME /var/www/reports/slow.php;
done

2023-04-21 07:29 UTC, KrawczowaKris commented on chapter3/php-fpm.conf
> +[slow]
done

2023-04-21 07:47 UTC, KrawczowaKris commented on chapter3/run.sh
> +curl https://localhost/reports/fast
done

2023-04-24 20:26 UTC, dmitry-mightydevops requested changes
you misunderstood my previous comments - pls re-read them. Right now implementation is not correct. Your previous implementation was right path. This one is not.

2023-04-24 20:26 UTC, dmitry-mightydevops commented on chapter3/nginx.conf
> +			fastcgi_pass reports;
your slow page should `fastcg_pass` into slow pool. You should have two different pools per 2 locations

2023-04-24 20:26 UTC, dmitry-mightydevops commented on chapter3/php-fpm.conf
> -pm.max_children = 1
why removed?

2023-04-24 20:27 UTC, dmitry-mightydevops commented on chapter3/php-fpm.conf
> +[slow]
@KrawczowaKris you should not remove the slow pool. Slow pool should define proper timeouts for workers using `admin` calls to override changes in php.ini.

2023-04-24 20:28 UTC, dmitry-mightydevops requested changes
and you still have duplicates in php.ini

php.ini should not have duplicated instructions even if the value is the same
![image](https://user-images.githubusercontent.com/70822710/234109189-446dff93-ed24-4cc4-8b0c-8c4ef39b00fb.png)

that lead to side effects. Someone will modify the top value and will not notice the bottom value exists - as a result it will be still 30s.

2023-04-24 20:30 UTC, dmitry-mightydevops requested changes

2023-04-24 20:30 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +curl -w " %{time_total}" https://localhost/reports/fast
use time

2023-04-24 20:30 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +curl -w " %{time_total}" https://localhost/reports/slow
use time

2023-04-24 20:30 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +curl -w " %{time_total}" https://localhost/reports/slow
```
on ☸ crossingguard-staging-eks (ci) saritasa-devops-camp on 🌱 main [?] 
➜ time curl -I 'Host: theproducebox.com'  https://54.235.197.83 --insecure
curl: (3) URL using bad/illegal format or missing URL
HTTP/1.1 301 Moved Permanently
Date: Mon, 24 Apr 2023 20:29:57 GMT
Server: Apache
X-Powered-By: PHP/7.4.15
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Pingback: https://theproducebox.com/xmlrpc.php
X-Redirect-By: WordPress
Set-Cookie: PHPSESSID=brbhv92f99030s2ujahv8lpqet; path=/
X-Frame-Options: SAMEORIGIN
Location: https://theproducebox.com/
Content-Type: text/html; charset=UTF-8

curl -I 'Host: theproducebox.com' https://54.235.197.83 --insecure  0.01s user 0.01s system 2% cpu 0.558 total

```

in this case we get `0.01s user 0.01s system 2% cpu 0.558 total` - which is what we need

2023-04-25 12:23 UTC, KrawczowaKris commented on chapter3/run.sh
> +curl https://localhost/reports/fast
done

2023-04-26 08:26 UTC, KrawczowaKris commented on chapter3/php-fpm.conf
> +[slow]
remade

2023-04-26 08:27 UTC, KrawczowaKris commented on chapter3/nginx.conf
> +			fastcgi_pass reports;
remade

2023-04-26 08:28 UTC, KrawczowaKris commented on chapter3/php-fpm.conf
> -pm.max_children = 1
remade

2023-04-26 08:33 UTC, KrawczowaKris commented on chapter3/run.sh
> +curl -w " %{time_total}" https://localhost/reports/fast
remade

2023-04-26 08:34 UTC, KrawczowaKris commented on chapter3/run.sh
> +curl -w " %{time_total}" https://localhost/reports/slow
remade

2023-04-26 08:47 UTC, KrawczowaKris commented on chapter3/run.sh
> +sleep 3
did not quite understand what is needed

2023-04-26 13:50 UTC, dmitry-mightydevops requested changes

2023-04-26 13:50 UTC, dmitry-mightydevops commented on chapter3/php-fpm.conf
> +request_terminate_timeout=630s
that is a different setting, which will KILL the worker after the desired timeout - we don't want the kill. Look into php.ini max_execution_time and set it via `php_admin_value`
https://code.tutsplus.com/tutorials/how-to-increase-max_execution_time-in-php--cms-37017

2023-04-26 13:50 UTC, dmitry-mightydevops commented on chapter3/php-fpm.conf
> +request_terminate_timeout=630s
1. so you set max_execution_time in fast pool = 60s  and you set max_execution_time = 600s in the slow pool
2. then you need to set [fastcgi_read_timeout](https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout) to 60 and 600 in the respective server/location contexts.

2023-04-26 13:52 UTC, dmitry-mightydevops commented on chapter3/run.sh
> +sleep 3
so your run.sh will not work if for example nginx started in 5s. That's why you need to have a `while` block in the code.

2023-04-27 08:01 UTC, KrawczowaKris commented on chapter3/run.sh
> +sleep 3
added

2023-04-27 08:36 UTC, KrawczowaKris commented on chapter3/php-fpm.conf
> +request_terminate_timeout=630s
remade

2023-04-28 20:48 UTC, dmitry-mightydevops requested changes

2023-04-28 20:48 UTC, dmitry-mightydevops commented on chapter3/php.ini
> +php_admin_value max_execution_timeout = 60s
no need to have this in php.ini
only in php-fpm pool

2023-05-02 03:52 UTC, KrawczowaKris commented on chapter3/php.ini
> +php_admin_value max_execution_timeout = 60s
done

2023-05-02 05:50 UTC, dmitry-mightydevops approved these changes

2023-05-02 06:17 UTC, merged