feat: compile distroless python3 OOM container
KrawczowaKris/devops-camp-2023 pull request #15
Opened 2023-04-25 10:54 UTC by KrawczowaKris

# Summary
## Test Task
Compile container using distroless base python3 image https://github.com/GoogleContainerTools/distroless

See python files in testtask folder.

What you will need to do:
-  setup pre-commit in the folder to run https://github.com/hadolint/hadolint checks against any Dockerfiles
        don't open any PR if your Dockerfile does not pass validation from the linter.
-  provide README.md with instructions how to run/test your work
-  create Makefile with the following targets:
        - `build`
        - `run`
            `run` target should accept parameter `limit` that will set the desired max memory limit for the running docker container
            if such parameter is not set, a default value of 100m should be used
-  make run should start the docker container and output content similar to
```
    Usage over time: [20.67578125, 20.67578125, 35.30078125, 50.17578125, 64.80078125, 79.55078125, 94.30078125, 20.734375]
    Peak usage: 94.30078125
```
-  make run with optional argument for memory set at 30m should understand that container exited by error and in this case output the following line
```
    {exited false false false true false 0 137  2023-04-17T00:50:11.053754525Z 2023-04-17T00:50:13.721847306Z <nil>}
```
which is content of the docker State value.

## my results
`make run`

**output:**
```
Usage over time: [22.12890625, 22.16796875, 36.51171875, 50.83984375, 65.453125, 79.890625, 94.328125, 22.2890625]
Peak usage: 94.328125
```
`make run MEMORY_LIMIT=30M`
**output:**
```
{exited false false false true false 0 137  2023-04-25T10:53:29.528821529Z 2023-04-25T10:53:29.967758705Z <nil>}
```

2023-04-25 19:38 UTC, dmitry-mightydevops requested changes

2023-04-25 19:38 UTC, dmitry-mightydevops commented on chapter4/compile-distroless/Dockerfile
> +COPY --from=build-env /usr/local /usr/local
that is not safe - only copy what is python related files changes on line 5 above.

2023-04-25 19:38 UTC, dmitry-mightydevops commented on chapter4/compile-distroless/Dockerfile
> +FROM gcr.io/distroless/python3:debug
don't use debug for prod

2023-04-25 19:38 UTC, dmitry-mightydevops commented on chapter4/compile-distroless/Makefile
> +run:
1. your `run` should work even without MEMORY_LIMIT passed.
2. extract `memory-container` value into makefile constant.

2023-04-26 09:38 UTC, KrawczowaKris commented on chapter4/compile-distroless/Dockerfile
> +COPY --from=build-env /usr/local /usr/local
remade

2023-04-26 10:06 UTC, KrawczowaKris commented on chapter4/compile-distroless/Makefile
> +run:
I don't quite understand the first comment

2023-04-26 13:37 UTC, dmitry-mightydevops commented on chapter4/compile-distroless/Makefile
> +run:
correct

2023-04-26 13:38 UTC, dmitry-mightydevops approved these changes

2023-04-27 04:41 UTC, merged