feat: t2 - generate kustomization.yaml
KrawczowaKris/devops-camp-2023 pull request #2
Opened 2023-03-29 12:54 UTC by KrawczowaKris

Task:
https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter2%20-%20bash%20basics/l1%20-%20bash%20basics.md#t2---generate-kustomizationyaml

2023-03-30 09:04 UTC, kseniyashaydurova requested changes

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	then echo "Please enter arguments"
Please always make clear error messages for the end user

```suggestion
	then echo "No arguments passed. Please add repositories names to proceed."
```

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF > ~/github_repos/devops-camp-2023/kustomization.yaml
hardcoded path again

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository() {
I think this function should be better named like 

```suggestion
generate_repository_kustomization_config() { 
```

or smth similar, so it would be clear what it does from its name

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	ssh-keygen -t ed25519 -N "" -f ~/github_repos/devops-camp-2023/ssh-keys/$name_repository-deploy-key.pem
Why not to put it to `generate_repository` function? and update its name to smth more appropriate?

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build ~/github_repos/devops-camp-2023 > ~/github_repos/devops-camp-2023/output.yaml
hardcoded paths

2023-03-30 09:04 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	ssh-keygen -t ed25519 -N "" -f ~/github_repos/devops-camp-2023/ssh-keys/$name_repository-deploy-key.pem
hardcoded paths

2023-03-30 09:04 UTC, kseniyashaydurova commented on .gitignore
> +/ssh-keys
Why not `repos` like it was written in the task?

2023-03-30 10:23 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# generate_repository -- takes a repository name and generates a repository
done

2023-03-30 10:30 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	local name_repository=$1
done

2023-03-30 10:37 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	local name_repository=$1
do

2023-03-30 10:41 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF >> ~/github_repos/devops-camp-2023/kustomization.yaml
done

2023-03-30 10:43 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	then echo "Please enter arguments"
done

2023-03-30 10:43 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF > ~/github_repos/devops-camp-2023/kustomization.yaml
done

2023-03-30 10:44 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository() {
done

2023-03-30 10:49 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build ~/github_repos/devops-camp-2023 > ~/github_repos/devops-camp-2023/output.yaml
done

2023-03-30 10:49 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +	ssh-keygen -t ed25519 -N "" -f ~/github_repos/devops-camp-2023/ssh-keys/$name_repository-deploy-key.pem
done

2023-03-30 11:07 UTC, KrawczowaKris commented on .gitignore
> +/ssh-keys
corrected

2023-04-03 04:51 UTC, kseniyashaydurova requested changes

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF >> /repos/kustomization.yaml
```suggestion
  cat << EOF >> /repos/kustomization.yaml
```

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  ssh-keygen -t ed25519 -N "" -f /repos/ssh-keys/$repository_name-deploy-key.pem
1. We don't need to have `ssh-keys` folder inside `repos`
2. Please add constant for path to `repos` folder (i.e. where you create kustomization.yaml and ssh keys itself)
3. Let's hide SSH key generation output and update command to not ask user to overwrite existing SSH key, i.e. let's force SSH key overriding
![image](https://user-images.githubusercontent.com/26448672/229414024-83d197dc-990e-4f31-b8f3-c73f9a8bc8d7.png)

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF > /repos/kustomization.yaml
Please use also constant for kustiomization file path

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +REPOSITORY_NAMES=$*
I think you can avoid defining separate `REPOSITORY_NAMES` var, which you use only once, so let's just write `$*` in a loop instead of adding new variable for just a one place

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build $FOLDER_PATH > /repos/output.yaml
Please don't hardcode `repos` path

2023-04-03 04:51 UTC, kseniyashaydurova commented on .gitignore
> +
why do you need this empty file then?

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH="/home/nadya/github_repos/devops-camp-2023"
Your script will work only at your computer, so it won't work anywhere else and there is no profit in such a script. So let's just use current user's dir for whole this script workflow

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  ssh-keygen -t ed25519 -N "" -f /repos/ssh-keys/$repository_name-deploy-key.pem
Now you script creates `repos` folder with its content in root Linux dir, which is incorrect. Let's reorganize codes to create `repos` folder in current path

2023-04-03 04:51 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build $FOLDER_PATH > /repos/output.yaml
It seems this command doesn't work? 
![image](https://user-images.githubusercontent.com/26448672/229414366-c79620c0-5468-4ace-ae9d-a79e98711a90.png)

2023-04-03 05:28 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF >> /repos/kustomization.yaml
done

2023-04-03 06:08 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF >> /repos/kustomization.yaml
done

2023-04-03 06:15 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat << EOF > /repos/kustomization.yaml
done

2023-04-03 06:19 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +REPOSITORY_NAMES=$*
done

2023-04-03 06:19 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build $FOLDER_PATH > /repos/output.yaml
done

2023-04-03 06:26 UTC, KrawczowaKris commented on .gitignore
> +
done

2023-04-03 06:26 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH="/home/nadya/github_repos/devops-camp-2023"
done

2023-04-03 06:26 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  ssh-keygen -t ed25519 -N "" -f /repos/ssh-keys/$repository_name-deploy-key.pem
done

2023-04-03 06:27 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kustomize build $FOLDER_PATH > /repos/output.yaml
done

2023-04-05 04:34 UTC, kseniyashaydurova requested changes

2023-04-05 04:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH=repos
I think `REPOS_PATH` or `KUSTOMIZATION_FOLDER_PATH` would be better and more clear as var name

2023-04-05 04:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH=repos
Let's always quote string vars values

2023-04-05 04:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +#!/bin/bash
1. Let's create `repos` folder if it doesn't exist
![image](https://user-images.githubusercontent.com/26448672/229980760-7ed40c22-844f-41c8-bf8f-9ad36f18e663.png)

2. If `repos` folder contains no ssh keys, script doesn't work
![image](https://user-images.githubusercontent.com/26448672/229981016-877378e1-fe45-4b7a-8f85-aa17c9c2ce67.png)

3. If `repos` already contains files here is what we have
![image](https://user-images.githubusercontent.com/26448672/229981774-8b05dafe-5331-4df5-bb04-ab3b80f31897.png)

2023-04-05 04:34 UTC, kseniyashaydurova commented on .gitignore
> +chapter2/tests/t2/repos/
Why not just `repos/*` ?

2023-04-05 04:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  ssh-keygen -y -t ed25519 -N "" -f $FOLDER_PATH/"$repository_name"-deploy-key.pem -q
Let's always use brackets for vars, i.e. `${FOLDER_PATH}` according to styleguide

2023-04-06 09:06 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH=repos
done

2023-04-06 09:07 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +FOLDER_PATH=repos
done

2023-04-06 09:14 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  ssh-keygen -y -t ed25519 -N "" -f $FOLDER_PATH/"$repository_name"-deploy-key.pem -q
done

2023-04-14 03:55 UTC, kseniyashaydurova requested changes

2023-04-14 03:55 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# generate_repository -- takes a repository name and generates a repository
Please update comments too with corresponding function name

2023-04-14 03:55 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +REPOS_PATH="./repos"
Let's always have constants in one separate block and not insert between them any commands

2023-04-14 03:55 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository_kustomization_config() {
Please add check that arguments are valid repo names, now I can generate broken manifests:
![image](https://user-images.githubusercontent.com/26448672/231937661-c445f843-45fb-4fc2-880f-d5c83a15095c.png)

2023-04-14 07:20 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# generate_repository -- takes a repository name and generates a repository
done

2023-04-14 07:22 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +REPOS_PATH="./repos"
done

2023-04-14 07:44 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository_kustomization_config() {
done

2023-04-26 07:52 UTC, roman-mightydevops requested changes

2023-04-26 07:52 UTC, roman-mightydevops commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository_kustomization_config() {
```
➜ ./test.sh repo devops-camp-2023 'my repo' my
devops-camp-2023 is invalid repository name
Error: merging from generator &{0xc0002aa380 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"Secret", isClusterScoped:false}, Name:"repo", Namespace:"argo-cd"} exists; behavior must be merge or replace

```
Something isn't working. I'm sure that 'devops-camp-2023' is a valid repo name :)

2023-05-03 03:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# generate_repository -- takes a repository name and generates a repository
Please also fix the same in 12th line

2023-05-03 03:34 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository_kustomization_config() {
I also don't see that it is fixed
![image](https://user-images.githubusercontent.com/26448672/235828066-bb94b81c-888b-4bc0-b0df-4e267402cb75.png)

2023-05-03 03:34 UTC, kseniyashaydurova requested changes
Please fix the rest comments

2023-05-04 05:14 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# generate_repository -- takes a repository name and generates a repository
done

2023-05-04 05:31 UTC, KrawczowaKris commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +generate_repository_kustomization_config() {
remade

2023-06-05 05:35 UTC, kseniyashaydurova approved these changes

2023-06-05 05:36 UTC, kseniyashaydurova approved these changes

2023-06-05 06:05 UTC, roman-mightydevops approved these changes

2023-06-13 03:42 UTC, merged