feat: terraform site
KrawczowaKris/devops-camp-2023 pull request #20
Opened 2023-06-02 05:31 UTC by KrawczowaKris

# Summary
## Test Task
**that means utilizing terraform:**
- create mysql database
  - use random provider to generate random mysql admin password
  - export that password in outputs.tf
- create acm cert
- generate ssh key
  - do not store SSH key locally
  - do not push SSH key into your remote git repo, so add `.gitignore` properly to your file.
- create 2 ec2 instances
  - export instance_ids as list into your outputs.tf
- deploy wordpress using USERDATA of the EC2 instances
- create EFS instance and mount it in the EC2 instance via fsdata
  - export FS ID in the outputs.tf
- create ALB and target groups
  - export your ALB URL in the outputs.tf
- add Route53 record for your ALB URL
  - full record FQDN in the outputs.tf
- Use <https://developer.hashicorp.com/terraform/language/resources/provisioners/remote-exec> and <https://developer.hashicorp.com/terraform/language/resources/provisioners/connection>  with SSH KEY generated above to run any commands on the instance (such as if you need to run any SQL commands to update wordpress settings with proper domains)
  - no need to install any plugins/image gallery
  - your wordpress should work with just a demo post.
  - use random provider to generate random mysql admin password
  - export that password in outputs.tf
  

## Test calls

## test 1
curl https://test-student-user-exam.saritasa-camps.link
should output valid html content of the wordpress home

## test 2
curl https://test-student-user-exam.saritasa-camps.link/admin
should out admin login screen

## test 3
curl http://test-student-user-exam.saritasa-camps.link/
should timeout

## test 4
prove that both instances are joined in the load balancer by showing their nginx access logs output.

## Nuances of the implementation

- for DB password/Wordpress admin password use this: <https://registry.terraform.io/providers/hashicorp/random/latest/docs>
- for the DB / RDS use this module: <https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest>
- for the security group use this module: <https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest>
- for ec2 instance use this  module: <https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/latest>
- for efs use this module: <https://registry.terraform.io/modules/terraform-aws-modules/efs/aws/latest>
- for alb use this module: <https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest>
- for route53 records use this module: <https://registry.terraform.io/modules/terraform-aws-modules/route53/aws/latest>
- use any `data` providers offered by AWS terraform provider.
- to generate SSH Keys you can use this module <https://registry.terraform.io/modules/cloudposse/key-pair/aws/latest> or you can do bare atomic resources like the following example:

```hcl
resource "tls_private_key" "cluster" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "cluster" {
  key_name   = var.cluster_name
  public_key = tls_private_key.cluster.public_key_openssh
}

resource "local_sensitive_file" "ssh_private_key" {
  content              = tls_private_key.cluster.private_key_openssh
  filename             = "${path.cwd}/assets/private_keys/${var.cluster_name}.pem"
  file_permission      = "0600"
  directory_permission = "0700"
}

```
make sure your SSH keys are not pushed in your public repo, so create the following `.gitignore` file in the root of your git repository **before** the commit:

```sh
➜ cat .gitignore               
__pycache__
.git-crypt/
.idea/
.ssh/
.terraform/
.vscode
*.bak
*.pyc
*.tfstate
*.tfstate.backup
*.zip
.git_rev
*.pem
*.pub
*.log
assets/ssl
builds/
packer_cache
git-crypt-key

```

**Important**: Make sure your traffic is through the VPN. So reuse the same makefile I have. Use the same structure for folders as in this task. Implement only a single environment (`dev`)

## my result
https://nadezhda-niukina-user-exam.saritasa-camps.link/

2023-06-05 00:53 UTC, dmitry-mightydevops requested changes
Your and Dasha code are clones? I know that both of you work together, but your solutions can't be 2 sisters. 

My feedback to her also applies to your code as well - read the feedback in her PR and address as well.

https://github.com/darliiin/devops-camp-2023/pull/20#pullrequestreview-1461456024

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/config.tf
> +  }
always use latest versions of providers and modules when you create NEW tf solutions.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/config.tf
> +      Owner = var.client
you're not the client. client is saritasa.
use semantic names.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  sensitive   = true
very good

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = [module.wordpress_ec2["1"].id, module.wordpress_ec2["2"].id]
inflexible solution. 
use a variable like `var.wordpress_instances_count = 2` and use https://developer.hashicorp.com/terraform/language/meta-arguments/count `count` functionality to build dynamic instances and outputs.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'WP_SITEURL', 'https://nadezhda-niukina-user-exam.saritasa-camps.link/' );
don't hardcode. Pass this as the variable.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
why are you using `cache_` prefix? You're not using aws elasticache at all.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
ingress/egress rules are not part of the vars. They should be computed dynamically inside your terraform code.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
all your vars below are incorrectly prefixed.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +}
so what you're going to do if you have 3, 4,...10 instances? Each time copy/paste the code? That's not good.
You need to come up with solution that work properly WITHOUT any modifications REGARDLESS how many ec2 instances you want for your WPs

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
break this file into smaller onces
like
rds.tf
acm.tf
ec2.tf
security_groups.tf
alb.tf
locals.tf

etc.

2023-06-05 00:53 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +}
export into locals.tf
your code and code of daria - has a lot of similarities. So someone is copying. You or her?
there is no way - each one of you came up with the same structure.

2023-06-05 12:05 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/config.tf
> +  }
done

2023-06-05 12:05 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/config.tf
> +      Owner = var.client
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = [module.wordpress_ec2["1"].id, module.wordpress_ec2["2"].id]
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'WP_SITEURL', 'https://nadezhda-niukina-user-exam.saritasa-camps.link/' );
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +}
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +}
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +}
remade

2023-06-05 12:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
done

2023-06-05 12:14 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
> +}
we did together

2023-06-06 00:42 UTC, dmitry-mightydevops requested changes

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnets.wordpress.ids[2]
provide a better call for the subnet id without using `[2]` as this is not semantic, not readable.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    fqdn_record      = local.fqdn_record
no need to use `comma` at the end in tf maps.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    password_rds     = local.rds.random_pwd,
that should come from the module random or random resource.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    db_name          = local.rds.db_name,
that should come from tfvars

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    efs_id           = local.efs_id
that should come from the module. No need to proxy module exports via locals - pls address all values you pass into the template and keep `locals` only where it's absolutely necessary

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +    }
make data resource that will return you a target subnet. No need to use array of arrays - the code gets harder to read.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/local.tf
> +  }
no need to proxy rds data in locals

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/local.tf
> +    nonce_salt       = random_string.random["nonce_salt"].result
no need to proxy keys in locals - pass them directly into the template via `xxx=random_string.random["nonce_salt"].result` vs `xxx=local.wp_keys.some_name`

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  attributes = [var.project, each.value]
move this into labels.tf and remove main.tf - it has no purpose now.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = [for instance in module.wordpress_ec2 : instance.id]
learn how to use `*` operator in terraform to avoid for into array.
https://developer.hashicorp.com/terraform/language/expressions/splat

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  family                              = "${var.rds_engine}${var.rds_major_engine_version}"
should be in tfvars

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  port                                = "3306"
should be in variables.tf as default values with ability to override in tfvars.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "195.201.120.196/32"
don't hardcode

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Corporate IP address"
desc should say why this variable is needed, not only what it is.
Is it to ping this addr? Restrict the access? Ingress/Egress?

WHen you introduce the var - always think what questions other engineer may have seeing it for the first time. Don't expect that others will be "thrilled" to read entire source code to understand "WHY". Save their time - make them happy!

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Number of instances ec2"
not clean explanation
better would be
Number of wordpress instances under load-balancing

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
>    description = "Name of domen for site"
FQDN of the site (if you expect a fully qualified domain name here)

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
>    description = "Name of domen for site"
and I see that it is 
dns_name = "saritasa-camps.link"

so it is not a domain technically speaking - it is a `hosted_zone` so name the var properly.
hosted_zone - contains DNS records.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "VPC tags to place host into"
host or ec2 instances. Keep in mind in infrastructure - the documentation matters. Absence of good docs / inline comments / hints - means
- you will work much slower
- or you will be doing mistakes (which in turn == downtime) which is bad.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +variable "instance_ec2_type" {
wordress_ec2_instance_type 
is better
prefix all vars with `wordpress` if they're related to wordpress.

rds_ to db etc.

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +variable "instance_rds_class" {
wordpress_rds_instance_type so your naming is consistent to `wordress_ec2_instance_type`
or just rds_instance_type if we treat rds db as a more generic component

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +variable "list_labels_random_values" {
move this at the end of the variables.tf

2023-06-06 00:42 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [for instance in module.wordpress_ec2 : instance.tags_all.Name]
use splat * to build the values

2023-06-06 00:44 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +}
the biggest value for both of you - is to make mistakes. You will learn by "fixing" them. When the work is shared - the knowledge consumption is much less and a lot more fragile. So always do independent from others.

2023-06-06 04:49 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
> +  attributes = [var.project, each.value]
I can't run code without main.tf file

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
> +}
ok

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnets.wordpress.ids[2]
remade

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    fqdn_record      = local.fqdn_record
remade

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    password_rds     = local.rds.random_pwd,
remade

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    db_name          = local.rds.db_name,
remade

2023-06-06 06:11 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    efs_id           = local.efs_id
remade

2023-06-06 06:12 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/efs.tf
> +    }
remade

2023-06-06 06:12 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/local.tf
> +  }
remade

2023-06-06 06:12 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/local.tf
> +    nonce_salt       = random_string.random["nonce_salt"].result
remade

2023-06-06 06:15 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = [for instance in module.wordpress_ec2 : instance.id]
remade

2023-06-06 06:16 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/rds.tf
> +  family                              = "${var.rds_engine}${var.rds_major_engine_version}"
remade

2023-06-06 06:16 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/rds.tf
> +  port                                = "3306"
remade

2023-06-06 06:16 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "195.201.120.196/32"
remade

2023-06-06 06:16 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Corporate IP address"
remade

2023-06-06 06:17 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Number of instances ec2"
remade

2023-06-06 06:17 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
>    description = "Name of domen for site"
remade

2023-06-06 06:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +variable "instance_ec2_type" {
remade

2023-06-06 06:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +variable "instance_rds_class" {
remade

2023-06-06 06:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +variable "list_labels_random_values" {
remade

2023-06-06 06:20 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [for instance in module.wordpress_ec2 : instance.tags_all.Name]
remade

2023-06-06 17:14 UTC, dmitry-mightydevops requested changes

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "subnet_a" {
if you filter by specific AZ, then name the resource properly
i.e. `subnet_a -> subnet_az`

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instances" "ec2" {
you work with concrete ec2, which is `aws_instances.wordpress` would be prefer naming

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = module.wordpress_ec2[*].tags_all.Name
Name may change, filter by ID of the instance - it never changes.

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/alb.tf
> +  depends_on = [data.aws_instances.ec2]
besides using it as dependency - do you use it anywhere else `aws_instances.ec2`? If not - then it's bad design.
if you want dependency - use other module, i.e. module.wordpress_ec2 to emphasize that you need to wait for ec2 to be provisioned before creating LB for them.

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  depends_on = [module.wordpress_rds]
this module should also depend on wordpress_efs

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
remove this file - it's empty. Terraform doesn't need main.tf to be present. It will build a graph tree to runs ops based on resources in all tf files in this folder.

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instances" "ec2" {
it doesn't look like you really have any value for this data resource. I only saw it in depends_on and nowhere else.

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_rds_name                 = "nadezhda_niukina_user_db"
groups vars by prefix and make them following the order as defined in your variables.tf file

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_ec2_instance_ami_id = "ami-08333bccc35d71140"
- explain what that AMI ID is (name)
- place a link to the AMI ID details in AWS GUI in the docs.

2023-06-06 17:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_labels_random_values = ["auth_key", "secure_auth_key", "logged_in_key", "nonce_key", "auth_salt", "secure_auth_salt", "logged_in_salt", "nonce_salt"]
use multiline array and sort keys by name in ASC mode.

2023-06-06 17:18 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Corporate IP address"
@KrawczowaKris 
```
module "wordpress_rds_sg" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "4.17.2"
  name        = local.labels.wordpress_rds_sg
  description = "Security group for rds"
  vpc_id      = data.aws_vpc.target.id
  ingress_with_cidr_blocks = [
    {
      rule        = "mysql-tcp"
      description = "Open connection with mysql"
      cidr_blocks = var.ip_address
    },
```

so the name for the var is very generic

```
module "wordpress_rds_sg" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "4.17.2"
  name        = local.labels.wordpress_rds_sg
  description = "Security group for rds"
  vpc_id      = data.aws_vpc.target.id
  ingress_with_cidr_blocks = [
    {
      rule        = "mysql-tcp"
      description = "Open connection with mysql"
      cidr_blocks = var.eks_office_public_ip_address
    },
```

would provide a lot of value to the person reading the code

2023-06-07 04:04 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
> +  attributes = [var.project, each.value]
fixed the problem

2023-06-07 06:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Corporate IP address"
done

2023-06-07 06:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
done

2023-06-07 06:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Type of instance ec2"
done

2023-06-07 06:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "subnet_a" {
done

2023-06-07 06:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instances" "ec2" {
done

2023-06-07 06:51 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/alb.tf
> +  depends_on = [data.aws_instances.ec2]
done

2023-06-07 06:52 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +  depends_on = [module.wordpress_rds]
done

2023-06-07 06:55 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/main.tf
done

2023-06-07 06:55 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_rds_name                 = "nadezhda_niukina_user_db"
done

2023-06-07 06:55 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_ec2_instance_ami_id = "ami-08333bccc35d71140"
done

2023-06-07 07:36 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
there is a map, not an array

2023-06-07 07:38 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
there is a map, not an array
`aws_route53_record.record[*].fqdn` does not work

2023-06-07 19:27 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
@KrawczowaKris 
then convert map to array using `values`
https://developer.hashicorp.com/terraform/language/functions/values
and then use splat

there is also a useful func `keys` in relation to maps
https://developer.hashicorp.com/terraform/language/functions/keys

2023-06-07 19:32 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_labels_random_values = [
not semantic name. cryptic.
a. let's rename to `wordpress_secret_keys`
b. add description what that is inline in this file

2023-06-07 19:33 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [var.availability_zones[0]]
availability_zones can be easily pulled from the data resource
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones

no need to put in vars.

2023-06-07 19:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [var.availability_zones[1]]
in future - avoid using mutating objects, ie lists. Always use maps. Index in the list will change and you will get downtime as your plan will force you to rebuild and if engineer miss that - they will have downtime.

so the rule of thumb. If you want to use LIST to FILTER data and you expect the same results back - you're are doing something wrong.

If you need predictability of your solution - don't use mutating vars like lists.

2023-06-07 19:43 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/alb.tf
> +      backend_protocol = "HTTP"
style your code similarly.
below in http_listeners you have the following sequence of attrs:
- 1. port
- 2. protocol
- 3. other attrs

so use the same here in target_groups
[{
    backend_port = 80
    backend_protocol = HTTP
    name = 
    targets = ...
}]

in terraform code (as well as in kubernetes manifests) - the readability, the consistent sequence of attrs/keys is very very desired to avoid becoming the "YAML" developer.

2023-06-07 19:47 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +    "${data.aws_subnet.subnet_az.availability_zone}" = {
construct this map dynamically
i.e.

```
for subnet in [data.aws_subnet.subnet_az, data.aws_subnet.subnet_bz, data.aws_subnet.subnet_cz] 
....
```

then your code would be concise and clean

2023-06-07 19:48 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = random_password.rds_admin_password.result
sequence of attr is wrong compared to others

2023-06-07 19:49 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_NAME', '${db_name}' );
you used offset padding n lines 63-70, so use the same style here.

2023-06-08 03:57 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
thanks, done

2023-06-08 04:43 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_labels_random_values = [
done

2023-06-08 05:15 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [var.availability_zones[0]]
done

2023-06-08 05:17 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    // authentication unique keys and salts for wp-config.php
done

2023-06-08 05:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  #validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
done

2023-06-08 05:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [aws_route53_record.record[aws_acm_certificate.cert.domain_name].fqdn]
done

2023-06-08 05:28 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_NAME', '${db_name}' );
done

2023-06-08 05:35 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = random_password.rds_admin_password.result
done

2023-06-08 05:50 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/efs.tf
> +    "${data.aws_subnet.subnet_az.availability_zone}" = {
done

2023-06-08 05:53 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/alb.tf
> +      backend_protocol = "HTTP"
done

2023-06-08 07:20 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +    values = [var.availability_zones[1]]
ok

2023-06-08 20:07 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    auth_key         = random_string.random["auth_key"].result # authentication unique keys and salts for wp-config.php
pad comments on the right side with many spaces to the left to make it visible.
then it's easy to spot the comment. and if you have multiple comments - they should be under the same column in the file.

2023-06-08 20:11 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = random_password.rds_admin_password.result
1. value should come from the rds module. that way when I read the code I know more than just the random value source
2. the name of the output var should match the variables.tf. If you prefix with `db_..., rds_...` then your output value should be prefixed the same way.

2023-06-08 20:11 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userdata.tpl
> +define('DB_NAME',     '${db_name}' );
invalid padding

2023-06-08 20:11 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_NAME', '${db_name}' );
nope
![image](https://github.com/KrawczowaKris/devops-camp-2023/assets/70822710/fbce1b13-665d-4155-ba36-b8727cdd6e45)

2023-06-09 04:22 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_NAME', '${db_name}' );
done

2023-06-09 04:39 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +    auth_key         = random_string.random["auth_key"].result # authentication unique keys and salts for wp-config.php
done

2023-06-09 04:39 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/outputs.tf
> +  value       = random_password.rds_admin_password.result
done

2023-06-09 04:40 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/userdata.tpl
> +define('DB_NAME',     '${db_name}' );
done

2023-06-12 10:08 UTC, kseniyashaydurova requested changes

2023-06-12 10:08 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/route53.tf
> +  name    = aws_acm_certificate.cert.domain_name
Please add a separate `domain` var in locals or vars and use it everywhere to not have a dependency for route53 from ACM

2023-06-12 10:08 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/random.tf
> +resource "random_password" "rds_admin_password" {
Let's locate each new `random` resource directly in file/folder for which this random resource was created. So when you go to some module you can see all resources which are needed for this module

2023-06-12 10:08 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/random.tf
> +  │ generate password for rds                                             │е7ЕН
Please fix typo

2023-06-12 10:08 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +  user_data = templatefile("${path.cwd}/terraform/base/userdata.tpl", {
Please add similar indent for `=`

2023-06-12 10:08 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "5.1.0"
Let's use `~>` syntax for versions

2023-06-12 18:02 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +variable "wordpress_ec2_instances_count" {
@kseniyashaydurova I specifically asked to group the vars by prefix and add prefix to avoid using generic names.

2023-06-12 18:05 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +/*
@kseniyashaydurova they're not modules. They're already in the base folder and symlinked into the `env` folder properly.  Having proxy modules would make future maintenance complicated. In fact in new usummit implementation I'm getting rid of the module conception we have in the boilerplate now for this very reason.

2023-06-12 18:08 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule                     = "http-80-tcp"
@kseniyashaydurova same issue as with ssh - this module provides naming rules to reduce the boilerplate, which I requested to do.

see here:
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/43974e94067251ee464018288aa44862d0adba22/rules.tf#L72

2023-06-12 18:11 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule        = "https-443-tcp"
@kseniyashaydurova named rule already restricts it.
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/43974e94067251ee464018288aa44862d0adba22/rules.tf#L75

2023-06-12 18:11 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule        = "http-80-tcp"
@kseniyashaydurova named rule already restricts it.

2023-06-12 18:13 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  user_data = templatefile("${path.cwd}/terraform/base/userdata.tpl", {
good point. @KrawczowaKris pls always run `terraform fmt` with proper args before pushing code to the remote.
You can install this plugin in VSCode which will format on save.
https://cloudkatha.com/auto-format-terraform-code-in-visual-studio-code/

2023-06-13 03:55 UTC, KrawczowaKris commented on chapter5/terraform/Makefile
> +# ifndef AWS_REGION
done

2023-06-13 06:14 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "record" {
remade

2023-06-13 06:20 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/acm.tf
> +  domain_name       = "${var.owner}-exam.${var.hosted_zone}"
done

2023-06-13 07:40 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/efs.tf
> +  source          = "terraform-aws-modules/efs/aws"
done

2023-06-13 08:07 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_route53_zone" "zone_record" {
done

2023-06-13 08:09 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +eks_office_public_ip_address = "195.201.120.196/32"
done

2023-06-13 08:48 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +    {
done

2023-06-13 09:03 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/route53.tf
> +  name    = aws_acm_certificate.cert.domain_name
done

2023-06-13 09:06 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/random.tf
> +  │ generate password for rds                                             │е7ЕН
done

2023-06-13 09:49 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "5.1.0"
done

2023-06-14 04:41 UTC, kseniyashaydurova requested changes
1. Test 2 returns 404 status code instead of admin page 
![image](https://github.com/KrawczowaKris/devops-camp-2023/assets/26448672/c7e0128b-1c05-4226-b0a9-02514cb44647)

2. Test 3 also shows not timeout, but 301 response (not sure whether `timeout` was strict requirement for this task or not, because basically this workflow is correct)

3. Needs to make minor improvements, which I asked

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +resource "random_string" "random" {
Let's name it `wordpress_keys` or smth like this, so it would be clear in the state what kind of random is created

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule                     = "http-80-tcp"
ok, thanks!

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/efs.tf
> +      description              = "Open nfs with ec2 instance"
nfs?

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/local.tf
> +module "wordpress_instance_labels" {
Is it used somewhere? I don't see

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +  egress_with_cidr_blocks = [
@dmitry-mightydevops shouldn't we allow TCP traffic from DB only to `wordpress` instance SG? As I understand, otherwise we would be able to make TCP connects from DB to any places

2023-06-14 04:41 UTC, kseniyashaydurova commented on chapter5/terraform/.gitignore
> +__pycache__
please add tfversion file

2023-06-14 04:51 UTC, dmitry-mightydevops commented
> @dmitry-mightydevops shouldn't we allow TCP traffic from DB only to wordpress instance SG? As I understand, otherwise we would be able to make TCP connects from DB to any places

@KrawczowaKris @kseniyashaydurova yes we should.

2023-06-14 04:51 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  egress_with_cidr_blocks = [
Yes we should to limit the connection into rds only to sg of the wodpress ec2 instances

2023-06-14 07:52 UTC, roman-mightydevops requested changes

2023-06-14 07:52 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/alb.tf
> +  version            = "~> 8.6.0"
All modules should be pinned to a specific version. Yes, this constraint allows only minor updates, but we have it as a rule.

2023-06-14 07:52 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  version                = "~> 5.0.0"
Same as for previous modules

2023-06-14 07:52 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  version                             = "~> 5.9.0"
Same as for previous modules

2023-06-14 07:52 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "~> 5.1.0"
Same as for previous modules

2023-06-14 07:52 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "~> 5.1.0"
Same as for previous modules

2023-06-14 08:37 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +  egress_with_cidr_blocks = [
restricted

2023-06-14 08:43 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +resource "random_string" "random" {
done

2023-06-14 08:47 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/local.tf
> +module "wordpress_instance_labels" {
done

2023-06-14 08:53 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/alb.tf
> +  version            = "~> 8.6.0"
done

2023-06-14 08:54 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/ec2.tf
> +  version                = "~> 5.0.0"
done

2023-06-14 08:54 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/rds.tf
> +  version                             = "~> 5.9.0"
done

2023-06-14 08:54 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "~> 5.1.0"
done

2023-06-19 04:15 UTC, kseniyashaydurova requested changes

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/.terraform-version
> +1.4.6
Please add empty line at the end of each file (your linters should do it for you)

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/alb.tf
> +resource "aws_lb_target_group" "wordpress_tg_type" {
I am not sure, but do we need target groups when we set `redirect` in HTTP listener?

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/alb.tf
> +  target_groups = [
Is it needed for 80 port when we have redirect?

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/local.tf
> +  domain_name = join(module.wordpress_label.delimiter, [var.owner, "exam.${var.hosted_zone}"])
`exam` part shouldn't be hard coded, it should come from vars

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/variables.tf
> +variable "ekb_office_public_ip_address" {
It is better to add more common variable for it and make it flexible (list), so we can pass few ip addresses and call it `allowed_ec2_ssh_ips` or smth like this

2023-06-19 04:15 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "subnet_az" {
Did you try to define `data` dynamically with `for_each`? will it work?

2023-06-19 06:51 UTC, KrawczowaKris commented on chapter5/terraform/.terraform-version
> +1.4.6
done

2023-06-19 08:13 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/local.tf
> +  domain_name = join(module.wordpress_label.delimiter, [var.owner, "exam.${var.hosted_zone}"])
done

2023-06-19 08:28 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/alb.tf
> +  target_groups = [
instances should only work on port 80

2023-06-19 08:31 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/alb.tf
> +resource "aws_lb_target_group" "wordpress_tg_type" {
i think it needs

2023-06-19 08:40 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +variable "ekb_office_public_ip_address" {
done

2023-06-19 09:28 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "subnet_az" {
remade

2023-06-19 16:05 UTC, roman-mightydevops approved these changes

2023-06-20 08:20 UTC, kseniyashaydurova approved these changes
Please fix small moments

2023-06-20 08:20 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnet.subnets[data.aws_availability_zones.availability_zones.names[0]].id
Not nice that you hard coded it, now instances are created always in one AZ, please try to use https://developer.hashicorp.com/terraform/language/functions/element So you can pass `count` as index there

2023-06-20 08:20 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/variables.tf
> +variable "domain_postfix" {
Let's be `default=""`

2023-06-20 09:18 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +variable "domain_postfix" {
done

2023-06-20 21:25 UTC, dmitry-mightydevops requested changes

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "~> 5.1.0"
for each provider define the source and version, like you did for `random` otherwise tflint will error out.
https://github.com/terraform-linters/tflint

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      description = "Open ssh connection"
this should contain
cidr_blocks = "x.y.w.z/mask" list of IPs.

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_cidr_blocks = var.allowed_ec2_ssh_ips
this attr means: List of IPv4 CIDR ranges to use on all ingress rules
you don't want access over port 80 to this IPs.

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "0.0.0.0/0"
alb should not allow port 80 requests. Only 443

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  default     = ""
prefer all defaults in the `infra.auto.tfvars`, not in the variables.tf

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each          = toset(data.aws_availability_zones.availability_zones.names)
you don't get any benefits for this foreach. It's enough to pass just the vpc_id to get the same output set for this data resource.

If you would filter for limited set of AZs, but you get all.

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +domain_postfix = "exam"
domain_postfix, means suffix or saritasa-camps.link.exam

introduce fqdn for the domain like
wordpress_domain = exam.saritasa-camps.link
or rename this var like
`wordpress_subdomain_prefix`

again always think if your variable name is self-explanatory or not.

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +vpc_tags = {
vpc_tags_filter

2023-06-20 21:25 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  # who are already logged into the site
offset?

2023-06-22 04:51 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "~> 5.1.0"
done

2023-06-22 05:00 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +      description = "Open ssh connection"
done

2023-06-22 05:02 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_cidr_blocks = var.allowed_ec2_ssh_ips
done

2023-06-22 05:03 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "0.0.0.0/0"
done

2023-06-22 05:12 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/variables.tf
> +  default     = ""
done

2023-06-22 05:36 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +domain_postfix = "exam"
done

2023-06-22 05:40 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +vpc_tags = {
done

2023-06-22 05:44 UTC, KrawczowaKris commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  # who are already logged into the site
remade

2023-06-22 06:05 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each          = toset(data.aws_availability_zones.availability_zones.names)
how to do it?

2023-06-23 00:28 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each          = toset(data.aws_availability_zones.availability_zones.names)
well it doesn't work because you made a choice to have a complex structure. 
you need to use 

```hcl
data "aws_subnets" "wordpress" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.target.id]
  }
}
```

defined above, as it will contain all subnets, and you can query it

instead


**module "wordpress_ec2"**
```hcl
subnet_id = element(data.aws_subnets.wordpress.ids,  count.index)
```

something like this. 

```hcl
data "aws_subnet" "subnets" {
  for_each = toset(data.aws_subnets.wordpress.ids)
  id       = each.value
}
```


And then you need to refactor your efs module as well

```hcl
mount_targets = {
    for subnet in data.aws_subnet.subnets:
    subnet.availability_zone => {
      subnet_id = subnet.id
    }
  }
```

2023-06-23 00:30 UTC, dmitry-mightydevops approved these changes
Nadya,

this pr is CONDITIONALLY Approved (at the code level) once you perform the change as I left in my last open comment.

Once this done please commit to git remote and then prepare the video showing all actions:

- terraform destrory
- terraform apply
- curl queries (or real browser GUI) for the app

Use OBStudio in linux. It can record entire screen with voice. If DNS propagation takes time - pause OBS and then continue when DNS resolves.

2023-06-23 00:31 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each          = toset(data.aws_availability_zones.availability_zones.names)
you don't need a data source to pull all AZs once this change is done.

2023-06-23 08:13 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each          = toset(data.aws_availability_zones.availability_zones.names)
done

2023-06-23 08:18 UTC, KrawczowaKris commented
Link to record:
https://drive.google.com/file/d/1JWvhGhNlbveJIZgBW2dbPPDkLYtJtp0Q/view?usp=sharing

2023-06-25 18:48 UTC, dmitry-mightydevops requested changes

2023-06-25 18:48 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_availability_zones" "availability_zones" {
is this being used?

2023-06-25 18:54 UTC, KrawczowaKris commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_availability_zones" "availability_zones" {
remade

2023-06-25 18:56 UTC, dmitry-mightydevops approved these changes

2023-06-27 03:23 UTC, kseniyashaydurova approved these changes

2023-06-28 19:50 UTC, dmitry-mightydevops commented
@KrawczowaKris pls terminate all resources in the AWS Camp account created
- via terraform
- or manually in early tasks:
  - load-balancers
  - certificates
  - security groups
  - ec2 instances
  - rds instances
  - elasticache etc

2023-06-29 09:54 UTC, merged