feat: terraform module
KrawczowaKris/devops-camp-2023 pull request #21
Opened 2023-06-02 13:00 UTC by KrawczowaKris

# Summary
## Test Task
- fix the problem with existing implementation of modules. They're duplicating functionality of downloading the image and starting the container. So export that functionality into generic module stored in _modules/container and reuse it in the modules nginx and redis
  -  since the nginx implementation has local-exec provisioner, please build a proper way to delete generated index.html pages, yet using the "docker" module you will create above.
- open PR when ready

Link to task:
https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter6%20-%20terraform/l4%20-%20environments/environments.md#tasks-for-today

2023-06-05 10:59 UTC, kseniyashaydurova commented
@KrawczowaKris Please always add link to original task (so it would be easier for me and @roman-mightydevops to understand, what is needed). Please add this link to your PR description - https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter6%20-%20terraform/l4%20-%20environments/environments.md

2023-06-05 12:11 UTC, kseniyashaydurova requested changes

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +variable "container_image" {
I suggest to remove `container` prefix everywhere in variables of `container` module, because it is clear in `container` module from it name

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/locals.tf
> +locals {
Let's move this `locals.tf` content to `main.tf` file? I think it makes no sense to have separate `locals.tf` file with just one  var inside

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  container_ports = {
```suggestion
  container_ports = var.container_ports
```

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_host_path = "${abspath(path.root)}/../../${var.environment}"
Let's rewrite it to be similar to `ports` format? currently you have 2 similar things written in different ways

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
Let's move it to vars in `dev`

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +output "container_id_short" {
You already have a `container_id_short` output in `container` module, so you can just use it instead of duplication

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/outputs.tf
> +output "container_id_short" {
You already have a `container_id_short` output in `container` module, so you can just use it instead of duplication

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +  description = "ID of the Docker image"
Please follow the same indents concept everywhere

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
> +  type        = map(any)
Let's use `object` instead of `map`?

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/config.tf
> +terraform {
the same as above

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/main.tf
> +  container_ports = {
What if I would like to add shared volumes for redis in ``dev` env for example? You base `redis` modules doesn't allow to do this. the same is related to `nginx` module. You base modules should be flexible and allow to do any stuff related to docker (at least the base one from `container` module)

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/variables.tf
> +  description = "Value of the name for the Docker container"
Is it correct? Looks not

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/variables.tf
> +    error_message = "Container internal port should be less 1000 and external above or equal to 8000"
Is it correct? Looks like not

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/base/config.tf
> +terraform {
the same as above, also `docker` provider can be omitted here, because it is added as submodule

2023-06-05 12:11 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
Why we don't have the same `use_nginx` var?

2023-06-05 13:14 UTC, roman-mightydevops requested changes

2023-06-05 13:14 UTC, roman-mightydevops commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  }
This makes module not reusable, but they supposed to be. Move this check out of it.

2023-06-05 13:14 UTC, roman-mightydevops commented on chapter5/terraform-task-1/terraform/_modules/nginx/config.tf
> +    }
I believe it's redundant. But haven't tried to run - how do I run it, by the way? 🤔

2023-06-05 13:14 UTC, roman-mightydevops commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  provisioner "local-exec" {
You need a destroy provisioner too

2023-06-05 13:14 UTC, roman-mightydevops commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
> +    error_message = "Container name should be prefixed with saritasa-devops-camps-2023-"
Same as for container module.

2023-06-07 09:37 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/config.tf
> +terraform {
remade

2023-06-07 09:38 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  default = {
remade

2023-06-07 09:40 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/main.tf
> +resource "docker_image" "container" {
remade

2023-06-07 09:40 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/config.tf
> +terraform {
remade

2023-06-07 09:42 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/locals.tf
> +locals {
remade

2023-06-07 09:49 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/config.tf
> +terraform {
remade

2023-06-07 09:50 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  }
remade

2023-06-07 09:50 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/config.tf
> +    }
remade

2023-06-07 09:51 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
> +    error_message = "Container name should be prefixed with saritasa-devops-camps-2023-"
remade

2023-06-09 07:21 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/config.tf
> +terraform {
done

2023-06-09 07:54 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  type        = map(any)
done

2023-06-09 08:54 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  type        = map(any)
done

2023-06-09 09:58 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +variable "container_image" {
done

2023-06-09 11:06 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +variable "container_image" {
done

2023-06-09 11:55 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +variable "container_image" {
done

2023-06-09 12:57 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
`volumes_host_path` can't be moved to `dev.tfvars`

2023-06-09 12:58 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
> +  type        = map(any)
done

2023-06-13 11:15 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/main.tf
> +    command = "rm -rf '${self.volumes.*.host_path[0]}'"
remade

2023-06-13 11:22 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_host_path = "${abspath(path.root)}/../../${var.environment}"
done

2023-06-13 11:23 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +output "container_id_short" {
done

2023-06-13 11:25 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +  description = "ID of the Docker image"
done

2023-06-13 11:36 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/variables.tf
> +  description = "Value of the name for the Docker container"
remade

2023-06-13 11:38 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
remade

2023-06-13 11:38 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  provisioner "local-exec" {
done

2023-06-13 11:45 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/main.tf
> +  container_ports = {
done

2023-06-14 05:32 UTC, kseniyashaydurova requested changes

2023-06-14 05:32 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/.makerc
> +endef
Please add empty line at the end

2023-06-14 05:32 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/Makefile
> +
Please fix file ending here

2023-06-14 05:32 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/dev/modules
> +/home/nadya/github_repos/devops-camp-2023/chapter5/terraform-task-1/terraform/_modules
Unable to apply your terraform because of this bad link
![image](https://github.com/KrawczowaKris/devops-camp-2023/assets/26448672/81febdd2-5913-4715-96b9-ab832f2fc480)

2023-06-14 05:33 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  type        = map(any)
don't see that it is done for ports

2023-06-14 05:34 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
Why not?

2023-06-14 05:34 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +output "container_id_short" {
Don't see that it is done

2023-06-14 05:35 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/redis/outputs.tf
> +output "container_id_short" {
I don't see that it is done

2023-06-14 06:10 UTC, kseniyashaydurova requested changes

2023-06-14 06:10 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
No need for `use_redis` check here and below, because you already check it in `count`, so if it is false, no module would be created at all

2023-06-14 06:10 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.nginx.container_name != "" ? var.nginx.container_name : null
Please configure `null` defaults for `var.nginx.container_name` and below

2023-06-14 06:10 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/base/variables.tf
> +    container_name = optional(string)
try this

```
container_name = optional(string, null)
```

It will set `null` by default

2023-06-14 09:02 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/dev/modules
> +/home/nadya/github_repos/devops-camp-2023/chapter5/terraform-task-1/terraform/_modules
done

2023-06-14 09:04 UTC, KrawczowaKris commented on chapter5/terraform-task-1/.makerc
> +endef
done

2023-06-14 09:08 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
>    description = "Value of the name for the Docker container"
done

2023-06-14 09:13 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/variables.tf
> +variable "volumes_nginx" {
done

2023-06-14 09:14 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/variables.tf
>    description = "Value of the name for the Docker container"
done

2023-06-14 09:14 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/variables.tf
> +variable "volumes_redis" {
done

2023-06-14 09:28 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/outputs.tf
> +  value = var.use_nginx ? {
done

2023-06-14 09:28 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/outputs.tf
>  output "redis" {
done

2023-06-14 09:29 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/variables.tf
> +  description = "Do you need to speed up the perf using nginx?"
done

2023-06-14 09:30 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  description = "List fo volumes for docker container"
done

2023-06-14 09:36 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +    name_folder = "../../${var.environment}"
done

2023-06-14 09:37 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
>    description = "Value of the name for the Docker container"
done

2023-06-14 09:55 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/main.tf
>    ports {
done

2023-06-14 09:57 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/container/variables.tf
> +  type        = map(any)
why? seems to be done

2023-06-14 10:25 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
variables are not inserted

2023-06-14 10:42 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +output "container_id_short" {
do I need to delete the output `container_id_short` or what?

2023-06-14 10:42 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/_modules/redis/outputs.tf
> +output "container_id_short" {
above

2023-06-14 10:45 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/variables.tf
> +variable "nginx_volumes_container_path" {
done

2023-06-14 10:46 UTC, KrawczowaKris commented on chapter5/terraform-task-1/Makefile
> +
done

2023-06-14 10:48 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
done

2023-06-14 10:53 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
done

2023-06-14 10:53 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/main.tf
> +  container_name               = var.nginx.container_name != "" ? var.nginx.container_name : null
done

2023-06-14 10:53 UTC, KrawczowaKris commented on chapter5/terraform-task-1/terraform/base/variables.tf
> +    container_name = optional(string)
done

2023-06-14 11:52 UTC, roman-mightydevops approved these changes

2023-06-19 04:56 UTC, kseniyashaydurova requested changes
![image](https://github.com/KrawczowaKris/devops-camp-2023/assets/26448672/96a4de39-7250-43d2-b234-681511feac3a)

But you wrote that it is `optional` parm in vars (it is so when I use `use_redis=true`)

2023-06-19 04:57 UTC, kseniyashaydurova commented on chapter5/terraform-task-1/terraform/_modules/nginx/outputs.tf
> +output "container_id_short" {
I meant that you should reuse logic from your base `container` module, which already retuens short output, no need to repeat shortening

2023-06-20 08:14 UTC, kseniyashaydurova approved these changes

2023-06-20 21:40 UTC, dmitry-mightydevops approved these changes

2023-06-22 04:30 UTC, merged