feat: t4 - get filename without the extension
KrawczowaKris/devops-camp-2023 pull request #3
Opened 2023-03-30 07:01 UTC by KrawczowaKris

# Summary
## Test Task
**T4 - Get filename without the extension**
Script should get a folder as an argument and return all files (including in the nested directories) but without the extension.

## my results
`./chapter2-l2-t4-files-no-extensions.sh /home/nadya/fig`

**output:**
```
/home/nadya/fig/e
/home/nadya/fig/d
/home/nadya/fig/wer
/home/nadya/fig/qw/asd
/home/nadya/fig/qw/uop
/home/nadya/fig/fds/dfs
/home/nadya/fig/fds/rert/d
/home/nadya/fig/fds/rert/d
/home/nadya/fig/fds/rert/poi
/home/nadya/fig/sss/reter
/home/nadya/fig/sss/wertep
```

2023-04-05 07:58 UTC, kseniyashaydurova requested changes

2023-04-05 07:58 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +for file in $files; do
Not working correctly when there is a `.test` folder inside main folder:
![image](https://user-images.githubusercontent.com/26448672/230017816-e41b6d9c-8523-48a2-9baf-feb29ff39fc9.png)

I suppose that there should be output:
```
test/.test/
test/.test/1
test/.test/2
test/
test/1
test/2
```

2023-04-06 06:40 UTC, KrawczowaKris commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +for file in $files; do
done

2023-04-07 10:36 UTC, kseniyashaydurova requested changes

2023-04-07 10:36 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
Script works incorrectly still

![image](https://user-images.githubusercontent.com/26448672/230593926-a7204656-7c20-4b1d-9740-4b4b65a1d19a.png)

1. It incorrectly processes double extensions (i.e. in real life there can be `archive.tar.gz` files with double extensions)
2. It incorrectly processes spaces in files and folders names

2023-04-07 10:36 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +
Also I checked `node_modules` dir for curiosity and it also doesn't work correctly
![image](https://user-images.githubusercontent.com/26448672/230594199-8db815b8-e6cb-4567-b0e1-94c4a96932c6.png)

2023-04-07 10:36 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  if [[ "${file}" == *"/."* && \
Please separate this `magic` if condition to separate vars and name them properly, so we could see what kind of magic happens here, now it is too cryptic and needs comments too

2023-04-07 16:09 UTC, KrawczowaKris commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  if [[ "${file}" == *"/."* && \
done

2023-04-12 11:26 UTC, KrawczowaKris commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
done

2023-04-14 04:04 UTC, kseniyashaydurova approved these changes

2023-04-14 04:04 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    continue
I think continue is redundant here

2023-04-14 05:09 UTC, merged