feat: t5 - get all unique extensions of files
KrawczowaKris/devops-camp-2023 pull request #4
Opened 2023-03-30 08:46 UTC by KrawczowaKris

# Summary
## Test Task
**T5 - Get all unique extensions of files**
Script should get a folder as an argument and return a list of unique extensions of all files (including in the nested directories)

## my results
`./chapter2-l2-t5-get-file-unique-extensions.sh ~/fig`

**output:**
```
git
txt
fjdk
qwert
saqw
```

2023-04-05 08:34 UTC, kseniyashaydurova requested changes

2023-04-05 08:34 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +folder=$1
Let's follow style guide for constants

2023-04-05 08:34 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +for file in $files; do
Let's always write vars in this way `${file}`, otherwise it doesn't work correctly on Mac

2023-04-05 08:34 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
Something works incorrectly here
![image](https://user-images.githubusercontent.com/26448672/230026585-a805ae03-3095-4b89-81e8-668d61accd97.png)

2023-04-05 08:34 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +# Script should get a folder as an argument and return a list of unique extensions of all files
Also please make script to accept only one argument, no more, no less

2023-04-05 08:34 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "$file" == *.* && ! "${extensions[0]}" =~ $extension ]]; then
Please try to use `uniq` bash function to avoid having `extensions` array and check for extension existence there

2023-04-06 09:43 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +folder=$1
done

2023-04-06 09:47 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +for file in $files; do
I don't quite understand. The script throws errors when I do this

2023-04-06 09:50 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +# Script should get a folder as an argument and return a list of unique extensions of all files
done

2023-04-06 10:00 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "$file" == *.* && ! "${extensions[0]}" =~ $extension ]]; then
done

2023-04-07 10:50 UTC, kseniyashaydurova requested changes

2023-04-07 10:50 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
Still works like before
![image](https://user-images.githubusercontent.com/26448672/230596219-e39caeb6-d193-474d-9499-c85bc5d0542b.png)

2023-04-07 10:50 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "${file}" == *.* ]]; then
It is very very cryptic and hard to read, add comment for each your if condition

2023-04-07 11:41 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +for file in $files; do
done

2023-04-07 12:40 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
seems to have been fixed

2023-04-07 12:40 UTC, KrawczowaKris commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "${file}" == *.* ]]; then
done

2023-04-14 04:08 UTC, kseniyashaydurova approved these changes

2023-04-14 05:10 UTC, merged