feat: t6 - get only dirs of the files
KrawczowaKris/devops-camp-2023 pull request #5
Opened 2023-03-30 09:33 UTC by KrawczowaKris

# Summary
## Test Task
**T6 - Get only dirs of the files**
Script should get a folder as an argument and return a list of unique directories of all files (including in the nested directories). only -f option is allowed for the use of find command, i.e.: find /tmp -type f. Which should find all files in all nested dirs and then process the output by using expansion.

## my results
`./chapter2-l2-t6-get-file-unique-dirs.sh ~/fig`

**output:**
```
/home/nadya/fig
/home/nadya/fig/qw
/home/nadya/fig/fds
/home/nadya/fig/fds/rert
/home/nadya/fig/sss
```

2023-04-11 10:26 UTC, kseniyashaydurova requested changes

2023-04-11 10:26 UTC, kseniyashaydurova commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +#!/bin/bash
Script works incorrectly
![image](https://user-images.githubusercontent.com/26448672/231132967-85ca6e29-fa4e-45ab-a80d-2b2490479e47.png)

2023-04-11 10:26 UTC, kseniyashaydurova commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +done
Please always add 1 empty line at the end of each script

2023-04-11 10:31 UTC, kseniyashaydurova requested changes

2023-04-11 10:31 UTC, kseniyashaydurova commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +folder=$1
Please also force users to pass only 1 argument

2023-04-11 13:04 UTC, KrawczowaKris commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +done
done

2023-04-11 13:04 UTC, KrawczowaKris commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +folder=$1
done

2023-04-11 13:05 UTC, KrawczowaKris commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +dirs=( )
done

2023-04-12 10:46 UTC, KrawczowaKris commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +#!/bin/bash
done

2023-04-14 04:10 UTC, kseniyashaydurova approved these changes

2023-04-14 05:09 UTC, merged