feat: t7 - get only the filenames
KrawczowaKris/devops-camp-2023 pull request #6
Opened 2023-03-30 09:55 UTC by KrawczowaKris

# Summary
## Test Task
**T7 - Get only the filenames**
Script should get a folder as an argument and return a list of all unique files with extensions but without the absolute path (including in the nested directories). only `-f `option is allowed for the use of `find `command, i.e.: `find /tmp -type f`. Which should find all files in all nested dirs and then process the output by using expansion.

## my results
`./chapter2-l2-t7-get-unique-files.sh ~/fig`

**output:**
```
e.git
wer.txt
d.txt
asd.fjdk
uop.qwert
dfs
d.saqw
poi
reter.git
```

2023-04-11 10:29 UTC, kseniyashaydurova requested changes

2023-04-11 10:29 UTC, kseniyashaydurova commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +  if [[ ! "${uniq_files[0]}" =~ $name_file ]]; then
The same, please try to use bash `uniq` command instead of checking filename existence in array - https://linuxhint.com/bash_uniq_command/

2023-04-11 10:29 UTC, kseniyashaydurova commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +#!/bin/bash
Something works incorrectly here 
![image](https://user-images.githubusercontent.com/26448672/231133810-d75412b1-d19d-4493-9ac3-7b989f774c5b.png)

2023-04-11 10:31 UTC, kseniyashaydurova commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +# Script get a folder as an argument and return a list of all unique files
Please also force users to pass only 1 argument, no more, no less

2023-04-11 12:21 UTC, KrawczowaKris commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +# Script get a folder as an argument and return a list of all unique files
done

2023-04-12 10:52 UTC, KrawczowaKris commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +#!/bin/bash
done

2023-04-14 04:12 UTC, kseniyashaydurova approved these changes

2023-04-14 05:08 UTC, merged