feat: t8 - display new tcp listening connections in the range 10000-10100
KrawczowaKris/devops-camp-2023 pull request #7
Opened 2023-04-03 11:16 UTC by KrawczowaKris

# Summary
## Test Task
**T8 - Display new tcp listening connections in the range 10000-10100**

When you launch the script it should initially list all tcp connections in the port range 10000-10100 New found connections should be displayed in the console as soon as they're identified.
If I have NO listening connections in such port range, then I should display "No TCP listening sockets found bound to ports in 10000-10100 range" every N seconds.

2023-04-21 11:07 UTC, kseniyashaydurova requested changes

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
Please define port ranges as constants

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  sleep 5
Please define time sleep with constant

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
Script doesn't work correctly
![image](https://user-images.githubusercontent.com/26448672/233620663-e70230f6-a7d1-4dc1-a432-ba1490caa37b.png)

It never shows me `ss` command output, even if I listen appropriate TCP ports with nginx

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
Try to use command attributes shortands, like `-t` instead of `--tcp` and etc

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  while [[ "${k}" -le "${count_ports}" ]]; do
What happens here? It looks cryptic, is it really needed? If so, please add more comments

2023-04-21 11:07 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    k="${k}"+2
Why +2, not clear too

2023-04-21 11:14 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
done

2023-04-21 11:15 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  sleep 5
done

2023-04-21 11:25 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
done

2023-04-24 20:19 UTC, dmitry-mightydevops requested changes

2023-04-24 20:19 UTC, dmitry-mightydevops commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
1. ports can change over time - so don't hardcode them. Extract in the variables at the top of the script
2. you need to watch listen connections, i.e. `ss -ltnp`

2023-04-24 20:20 UTC, dmitry-mightydevops commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
@KrawczowaKris I don't see it's done

2023-04-28 11:43 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  while [[ "${k}" -le "${count_ports}" ]]; do
remade

2023-04-28 11:43 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    k="${k}"+2
remade

2023-04-28 11:44 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  ports=( $(ss --tcp sport ge 10000 and sport le 10100 | awk '{ print $4,$5,$6,$7 }') )
done

2023-04-28 11:45 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
remade

2023-04-28 20:16 UTC, dmitry-mightydevops requested changes
the script is not working as expected
![image](https://user-images.githubusercontent.com/70822710/235244902-92fbcd98-8f2b-4e90-a3cc-0fa68985fb60.png)

1. run script
2. no output - good
3. run `docker run --publish 10001:80 nginx` - get output. good
4. run `docker run --publish 10002:80 nginx` - got wrong output

```
comm: file 2 is not in sorted order
comm: input is not in sorted order
0.0.0.0:10002		0.0.0.0:*
0.0.0.0:10001		0.0.0.0:*
[::]:10002		[::]:*
[::]:10001		[::]:*

```

expected:

```sh
0.0.0.0:10002		0.0.0.0:*
[::]:10002		[::]:*
```

if needed you can simplify to work only with ipv4.

2023-04-28 20:16 UTC, dmitry-mightydevops commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +all_ports=""
prefer normal lowercase for the vars. THIS_NAMES_CAME_FROM90s.

2023-04-28 20:16 UTC, dmitry-mightydevops commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  new_port=$( comm -13 <(echo "${all_ports}") <(echo "${ports}") )
love that you have used `comm` :)

2023-05-02 05:52 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +all_ports=""
remade

2023-05-02 23:21 UTC, dmitry-mightydevops requested changes
incorrect results
https://jing.saritasa.com/DmitrySemenov/index.php?name=video_2023_05_02_pya40xm8.ogv

2023-05-03 03:43 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
Still has some problems:
![image](https://user-images.githubusercontent.com/26448672/235828836-d4195773-a3f3-456f-96a5-8bbea9093231.png)

2023-05-03 03:45 UTC, kseniyashaydurova requested changes
Still doesn't work as expected

2023-05-04 06:06 UTC, KrawczowaKris commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
I do not understand, should all ports be re-displayed when updating?

2023-05-10 22:55 UTC, dmitry-mightydevops approved these changes

2023-06-12 09:02 UTC, kseniyashaydurova approved these changes

2023-06-19 09:38 UTC, merged