feat: t3 - find namespaces without the backup
KrawczowaKris/devops-camp-2023 pull request #8
Opened 2023-04-04 10:58 UTC by KrawczowaKris

# Summary
## Test Task
**T3 - Find namespaces without the backup**

We need to come up with a prototype solution that will give us the list of kubernetes namespaces we haven't backed up. We have a special backup manifest that contains the configurationf for the backups. The configuration is in the schedules.[].includedNamespaces block of the file. 

We're supposed to run the following command:
`kubectl get ns -o="custom-columns=NAME:.metadata.name" --no-headers`
that will give us a list of all namespaces in the kubernetes cluster.

Implement the bash script that will find all namespaces in the cluster that has not been configured in the velero manifest. I.e. operation on sets.

**nuances:**
- your bash script should download these 2 gists using `curl` and pass them into stdout of other commands you're using.
- you can use any CLI tool from the distro you're using to calculate the diff between two data blocks and come up with the output above.
- you can use `yq` or `jq cli` if necessary for your ops.

## my results
`./chapter2-t3-velero-eks-diff.sh`

**output:**
```
aacct
aaoa-ari-cleara
arthrexvip
axia
camp-dotnet
camp-python
camp-unity
caregiver
ci-experiments
ci-experiments-apps
commlrning
debug
demo
dev
disvr
dogvr
enrgy
fallon-medica
faroeve
fbmm
firearm
github-inactivity
igntpb
inkus
insights-agent
interesnee
jenkins
kubewatch
macroplate
mailhog
maunf
medvr
metrics-server
nrs
oprs
prfctpt
redis
rma
saritasa-android
saritasa-ios
saritasa-jira-qa-tool
saritasa-php
saritasa-python
saritasa-qa
saritasa-unity
scripta
sgvr
sportsthread
streetparking
tekton-pipelines-experiments
toro
tran
trapi
trivver
utd
utils
velero
vrcatchup
```

2023-04-05 04:03 UTC, kseniyashaydurova requested changes

2023-04-05 04:03 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +for namespace in $namespaces; do
Let's try to echo `$namespaces` as separate lines without loop, let's find some bash utilities which will allow us to do it in one line
```
echo "${namespaces}" | ...
```

2023-04-06 06:47 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +namespaces=$(curl -sSL \
done

2023-04-06 07:40 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +while read conf_ns; do
done

2023-04-06 07:52 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +for namespace in $namespaces; do
done

2023-04-06 08:34 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +configuration_backups=$(curl -sSL \
done

2023-04-07 10:45 UTC, kseniyashaydurova requested changes
Please make few minor changes

2023-04-07 10:45 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file_existence "kubernetes-namespaces.txt" "${kubernetes_namespaces}"
It doesn't work when 2d file doesn't exit
![image](https://user-images.githubusercontent.com/26448672/230595042-e06a018e-14f1-460b-adba-cec4108a8225.png)

2023-04-07 10:45 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +kubernetus_namespaces=$(curl -sSL \
```suggestion
kubernetes_namespaces=$(curl -sSL \
```

2023-04-07 10:48 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +echo $kubernetus_namespaces | tr " " "\n"
```suggestion
echo ${kubernetus_namespaces} | tr " " "\n"
```

2023-04-07 11:19 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +echo $kubernetus_namespaces | tr " " "\n"
done

2023-04-07 11:20 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +kubernetus_namespaces=$(curl -sSL \
done

2023-04-07 11:22 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file_existence "kubernetes-namespaces.txt" "${kubernetes_namespaces}"
![Uploading image.png…]()

2023-04-07 11:25 UTC, KrawczowaKris commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file_existence "kubernetes-namespaces.txt" "${kubernetes_namespaces}"
![image](https://user-images.githubusercontent.com/72573143/230600919-b40ee69c-9413-4d59-b189-4c0930cc3772.png)
Seems to be working for me

2023-04-14 03:59 UTC, kseniyashaydurova approved these changes

2023-04-14 05:07 UTC, merged